---

system_packages:
  - acpi
  - acpid  # acpi events handler.sh (jack, lid toggle...)
  - adobe-source-code-pro-fonts
  - android-tools
  - ansible
  - apache-tools  # htpasswd
  - arandr
  - arc-gtk-theme
  - aria2
  - asciiquarium
  - autorandr
  - aws-cli
  - baobab
  - base
  - bash
  - bash-completion
  - bat  # cat with syntax highlighting
  - bc
  - bind
  - binwalk
  - bitwarden-cli
  - breeze-hacked-cursor-theme
  - brightnessctl
  - caprine
  - cava-git
  - checkbashisms
  - chromium
  - clipster
  - clusterssh
  - cmake
  - code  # visual studio code
  - color-picker
  - compton
  - convmv
  - cryptsetup
  - ctags
  - curl
  - ddcutil
  - dialog
  - diff-so-fancy
  - discord
  - dmidecode
  - dnscontrol-bin
  - docker
  - docker-compose
  - dosfstools  # gparted fat32 support
  - dunst
  - ed  # Ed is the standard text editor.
  - eslint
  - exa
  - exfat-utils
  - fd  # find alternative
  - ffmpegthumbnailer  # video files previews
  - file-roller  # archive manager
  - firefox
  - flat-remix
  - fping
  - freetype2  # font files previews
  - funny-manpages
  - fwupd  # firmware upgrade tool
  - fzf
  - gcc
  - gimp
  - git
  - git-open-git  # https://github.com/paulirish/git-open
  - gnome-sound-recorder
  - gnu-netcat
  - gnupg
  - gparted
  - gpicview
  - grcat  # generic colouriser
  - gsimplecal
  - gtk3
  - gvfs-smb  # mount samba shares
  - hsetroot  # xsetroot but works
  - htop
  - httpie
  - hugin  # photo tools
  - i3blocks
  - i3-gaps
  - icedtea-web  # open java jnlp files and other weird 90's things
  - imv  # image viewer
  - informant  # archlinux news pacman hook
  - inkscape
  - intel-ucode  # intel processors microcode updates
  - jdk-openjdk
  - jpegoptim
  - jq  # CLI JSON parser
  - jre-openjdk
  - kanshi  # wayland monitor autoconfigurator (autorandr)
  - kitty
  - libappindicator-gtk3
  - libinput-gestures
  - libreofice-still
  - libu2f-host  # U2F security key communication
  - libva-utils
  - libva-vdpau-driver
  - linux-firmware  # linux proprietary drivers
  - linux-lts
  - linux-lts-headers
  - lite-xl  # graphical text editor
  - lostfiles  # find files not owned by any package
  - lsof
  - lxrandr-gtk3
  - maim
  - make
  - mediainfo
  - mktorrent
  - mlocate
  - mosh
  - mpc
  - mpd
  - mpdscribble
  - mpv
  - mtools  # gparted fat32 support
  - mtr
  - ncdu
  - ncmpcpp
  - nemo
  - nemo-fileroller
  - nemo-mediainfo-tab
  - nemo-python
  - neofetch  # hipster swag
  - netcat
  - net-tools
  - nextcloud-client
  - nfs-utils
  - nmap
  - nodejs
  - nomacs
  - npm
  - ntfs-3g
  - openssh
  - p7zip
  - pacman-contrib  # checkupdates and paccache
  - pass  # for TOTP
  - pavucontrol
  - pdfgrep
  - perl-anyevent-i3
  - perl-image-exiftool
  - perl-json-xs
  - physlock  # secure TTY locker
  - pipewire
  - pipewire-pulse
  - playerctl-git
  - poppler-glib  # pdf files previews
  - pulseaudio
  - pv
  - python
  - python2
  - python-pip
  - qalculate-gtk  # graphical calculator
  - qrencode
  - rclone
  - redshift
  - ripgrep  # rg, ag alternative
  - rofi
  - rofimoji
  - rsync
  - rxvt-unicode
  - shellcheck
  - sieve-connect
  - signalbackup-tools-git
  - simplescreenrecorder
  - slack-desktop
  - snore-git  # sleep with feedback
  - sox  # play command
  - spotify  # https://download.spotify.com/debian/pubkey.gpg
  - strace
  - sudo
  - tcpdump
  - telegram-desktop
  - terraform
  - testdisk
  - testssl.sh
  - thefuck
  - the_silver_searcher  # ag
  - tlp  # laptop power management
  - tmux
  - tor
  - torbrowser-launcher
  - totp-cli
  - traceroute
  - trash-cli  # VSCode file deletion support (Electron7)
  - tree
  - trickle  # userspace bandwidth limiter
  - tumbler  # image files previews
  - udiskie
  - udisks2
  - unrar
  - unzip
  - urxvt-resize-font-git
  - usbutils
  - vim
  - vlc
  - weechat
  - wget
  - whois
  - wireless_tools
  - wireplumber
  - wmctrl
  - x11-ssh-askpass  # VSCode SSH authentication
  - xautolock
  - xclip
  - xf86-input-libinput
  - xorg-server
  - xorg-setxkbmap
  - xorg-xev
  - xorg-xinit
  - xorg-xinput
  - xorg-xkill
  - xorg-xprop
  - xorg-xrandr
  - xorg-xrdb
  - xorg-xwininfo  # i3-get-window-criteria.sh
  - yamllint
  - yarn
  - youtube-dl
  - yq  # yaml helper
  - zenity  # for custom UI dialogs
  - zip
  - zsh
  - zsh-completions  # yes there is a "s" unlike bash-completion :)

print_packages:
  - cups
  - cups-pdf
  - ghostscript
  - gsfonts
  - gtk3-print-backends
  - gutenprint

bluetooth_packages:
  - blueman  # bluetooth GUI applet
  - bluez  # system bluetooth implementation
  - bluez-utils
  - pulseaudio-bluetooth

font_packages:
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ttf-dejavu
  - ttf-font-awesome-4  # i3bar icons

boot_packages:
  - systemd-boot-pacman-hook

network_packages:
  - dnsmasq  # Local DNS cache
  - networkmanager
  - network-manager-applet
  - networkmanager-openvpn
